require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.onedark") -- default colorscheme
-- require("user.gruvbox")
require("user.cmp")
-- require("user.coc")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
-- require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
-- require("user.indentline")
-- require("user.alpha") -- default ui when no file is opened
require("user.whichkey")
require("user.autocommands")
